version: '3'
services:
  app:
    container_name: huddle
    environment:
      - MONGO=127.0.0.1:27107
    restart: always
    build: .
    ports:
      - '80:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27017:27017'
