name: GCP Cloud Run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mapfap/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        CLOUDSDK_CORE_PROJECT: ao00-254402
    - uses: mapfap/gcloud/cli@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        CLOUDSDK_CORE_PROJECT: ao00-254402
      with:
        args: builds submit --tag gcr.io/ao00-254402/nodeapp
     - uses: mapfap/gcloud/cli@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        CLOUDSDK_CORE_PROJECT: ao00-254402
      with:
        args: beta run deploy --image gcr.io/ao00-254402/nodeapp --platform managed      
